# Generated by Django 4.2.4 on 2024-03-29 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='newstock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnm', models.CharField(max_length=25)),
                ('mpr', models.IntegerField()),
                ('mim', models.FileField(upload_to='pictures')),
                ('cat', models.CharField(max_length=25)),
                ('bran', models.CharField(max_length=25)),
                ('des', models.TextField()),
                ('dis', models.CharField(max_length=25)),
                ('mfg', models.DateField()),
                ('exp', models.DateField()),
                ('qt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='shop_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pasw', models.CharField(max_length=25)),
            ],
        ),
    ]
