# Generated by Django 4.2.4 on 2024-03-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_cart_tbl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro', models.CharField(max_length=25)),
                ('qty', models.IntegerField()),
                ('prc', models.IntegerField()),
                ('tot', models.IntegerField()),
                ('fn', models.CharField(max_length=25)),
                ('cd', models.IntegerField()),
                ('ex', models.DateField()),
                ('cvv', models.CharField(max_length=25)),
            ],
        ),
    ]
